version: '3'

services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - prestashop-net
    restart: always

  prestashop:
    image: prestashop/prestashop:1.7.8
    container_name: prestashop
    environment:
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=admin
      - DB_NAME=prestashop
      - PS_FOLDER_ADMIN=adminpanel
    volumes:
      - psdata:/var/www/html
      - ./presta_key.crt:/etc/ssl/certs/presta_key.crt
      - ./presta_key.key:/etc/ssl/private/presta_key.key
      - ./prestashop-ssl.conf:/etc/apache2/sites-available/prestashop-ssl.conf
    command: /bin/bash -c "a2enmod ssl && a2ensite prestashop-ssl && apache2-foreground"
    depends_on:
      - mariadb
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - prestashop-net
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - prestashop-net
    restart: always
networks:
  prestashop-net:
volumes:
  dbdata:
  psdata: